# Generated by Django 6.0.7 on 2026-07-16 05:36
"""
BEGIN;
--
-- Rename field user on product to created_by
--
SET CONSTRAINTS "products_product_user_id_e04f062e_fk_users_user_id" IMMEDIATE; ALTER TABLE "products_product" DROP CONSTRAINT "products_product_user_id_e04f062e_fk_users_user_id";
ALTER TABLE "products_product" RENAME COLUMN "user_id" TO "created_by_id";
ALTER TABLE "products_product" ADD CONSTRAINT "products_product_created_by_id_dd4af40e_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='created_by',
        ),
    ]
