# Generated by Django 6.0.7 on 2026-07-16 18:48
"""
BEGIN;
--
-- Add field clothe_type to product
--
ALTER TABLE "products_product" ADD COLUMN "clothe_type" varchar(10) DEFAULT 'no type' NOT NULL;
ALTER TABLE "products_product" ALTER COLUMN "clothe_type" DROP DEFAULT;
COMMIT;
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_user_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="clothe_type",
            field=models.CharField(
                choices=[
                    ("no type", "No type"),
                    ("shirts", "Shirts"),
                    ("pants", "Pants"),
                    ("hoodies", "Hodies"),
                    ("hats", "Hats"),
                ],
                default="no type",
                max_length=10,
            ),
        ),
    ]
