# Generated by Django 6.0.7 on 2026-07-16 19:18
"""
BEGIN;
--
-- Alter field created_by on product
--
SET CONSTRAINTS "products_product_created_by_id_dd4af40e_fk_users_user_id" IMMEDIATE; ALTER TABLE "products_product" DROP CONSTRAINT "products_product_created_by_id_dd4af40e_fk_users_user_id";
ALTER TABLE "products_product" ALTER COLUMN "created_by_id" DROP NOT NULL;
ALTER TABLE "products_product" ADD CONSTRAINT "products_product_created_by_id_dd4af40e_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_clothe_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
